rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3

gemfile:
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile

matrix:
  exclude:
    - rvm: 2.6.3
      gemfile: gemfiles/5.0.gemfile
    - rvm: 2.6.3
      gemfile: gemfiles/5.1.gemfile

before_install:
  - gem update bundler
