rvm:
  - 2.2
  - 2.3
  - 2.4.1

gemfile:
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile

matrix:
  exclude:
  - rvm: 2.4.1
    gemfile: gemfiles/4.0.gemfile
  - rvm: 2.4.1
    gemfile: gemfiles/4.1.gemfile

before_install:
  - gem update bundler
