rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2

gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile

language: ruby
before_install: gem install bundler
before_script: bundle update
sudo: false
cache: bundler
